### ISSUE TITLE
Update not work

### ISSUE THREAD

**Issue by codeput** [crealitycloud/OctoPrint-CrealityCloud-With-Video#2]
The update process ends successfully but the old version remains installed, the pop-up window keeps saying that there is an update available.

**Comment by weinull** [comment]
> The update process ends successfully but the old version remains installed, the pop-up window keeps saying that there is an update available.

This is caused by the plugin author not modifying the version number, we can manually modify the version number to solve this problem.

**Step:**
1. Uninstall old versions of plugins.
2. Download the latest installation package.
3. Unzip the installation package, modify the "plugin_version" parameter in the "setup.py" file to the latest version number and save the file.
4. Manually install plugins using python.

**Comment by codeput** [comment]
It work, thank you.

Il dom 24 apr 2022, 04:45 weinull ***@***.***> ha scritto:
